apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-caddyfile
  namespace: grafana
  labels:
    {{- include "pysocha-site.labels" . | nindent 4 }}
    {{- include "pysocha-site.selectorLabels" . | nindent 4}}
data:
  Caddyfile: |-
    http://www.{{ .Values.domain}} {
      redir https://{{ .Values.domain}}
      log {
        output stdout
        format json
      }
    }

    http://{{ .Values.domain}} {
      root * {{ .Values.sitefilePath}}

      file_server
      log {
        output stdout
        format json
      }
    }

    :{{ .Values.healthCheck.port }} {
      respond {{ .Values.healthCheck.path }} 200 {
        body "OK"
        close
      }
    }

    :{{ .Values.metrics.port }} {
      metrics {{ .Values.metrics.path }}
    }