apiVersion: v1
kind: Service
metadata:
  name: {{ include "pysocha-site.fullname" . }}
  labels:
    {{- include "pysocha-site.labels" . | nindent 4 }}
spec:
  type: {{ .Values.http.servicetype }}
  ports:
    - port: {{ .Values.http.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "pysocha-site.selectorLabels" . | nindent 4 }}
